[package]
name = "blockchain_Rust"
version = "0.1.0"
authors = ["JNhua <hjntc59@qq.com>"]
edition = "2018"

[dependencies]
time="0.1.42"
rust-crypto = "0.2.36"
hex = "0.3.2"
json = "0.11.13"
serde = "*"
serde_derive = "*"
serde_json = "*"
canteen = "0.5.1"
urlparse = "0.7.3"